tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 8080
    onOpen: ignore
  - port: 9693
    onOpen: ignore
  - port: 9695
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker