tasks:
  - init: |
      GQL_ENDPOINT_CONSOLE="https://8080-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" docker-compose up

ports:
  - port: 8080
    visibility: public
    onOpen: ignore
  - port: 9693
    onOpen: ignore
  - port: 9695
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker